### ISSUE TITLE
IPInfoDB Support

### ISSUE THREAD

**Issue by m-cameron** [DavidePastore/ipinfo#7]
Do you have plan to support IPInfoDB.com API?

**Comment by DavidePastore** [comment]
Hi, I saw you have a PHP class in the API page. Why don't you create a public project with that class? I think that this project will be available only for ipinfo.io, but I'm open to hear the views of others.

**Comment by rvalitov** [comment]
I think this project should focus on IPInfo only. Universal aggregators that can work with different services already exist, for example, [Geocode](https://github.com/geocoder-php/Geocoder). It has support for IPInfo and IPInfoDB as requested by @m-cameron But such universal aggregators provide only general unified interfaces (the data fields that can be general and shared between all services), so that you can't access unique data that each service may provide. The strong part of this project is that it does what it does: a complete access to ipinfo and nothing else. A compact code without extra dependencies, etc.

**Comment by DavidePastore** [comment]
As @rvalitov said, I have no plans to add IPInfoDB.com support in this library.
